/**
 * Pre-computed stats from the full 110,000+ expert pool.
 * This file is auto-generated by scripts/generate-experts-100k.ts.
 * DO NOT EDIT MANUALLY.
 *
 * Generated at: 2026-03-09T14:57:32.009Z
 */

export const precomputedStats = {
  total: 110000,
  avgAccuracy: 65,
  avgCredibility: 67,
  highAccuracy: 27938,
  totalPredictions: 164092,
  correctPredictions: 68402,
  partialPredictions: 33298,
  overallAccuracyRate: 52,
  domainCounts: {"부동산":4448,"채권":7013,"헤지펀드":3270,"주식시장":15184,"외환":11441,"금리통화정책":13322,"한국경제":12391,"사모투자":3273,"경제안보":8172,"글로벌공급망":3501,"거시경제":17048,"원자재":6542,"국제금융":11210,"미중관계":4671,"가상자산":4206,"AI기술":10510,"반도체":5608,"재정정책":6078,"에너지":7007,"지정학리스크":1870} as Record<string, number>,
};
