/**
 * Pre-computed stats from the full 100,000 expert pool.
 * This file is auto-generated by scripts/generate-experts-100k.ts.
 * DO NOT EDIT MANUALLY.
 *
 * ★ 핵심 원칙: 과거 적중률이 55% 가중치로 신뢰도를 압도적으로 좌우
 * - 10만명 전문가 및 기관의 과거 예측 vs 실제 결과를 분석
 * - 적중률 상위 전문가의 현재 전망에 압도적 가중치 부여
 * - 이를 종합하여 AI가 확률적으로 미래를 예측
 *
 * Generated at: 2026-03-10T04:26:17.636Z
 */

export const precomputedStats = {
  total: 100000,
  avgAccuracy: 65,
  avgCredibility: 66,
  highAccuracy: 34094,
  eliteAccuracy: 18121,
  totalPredictions: 198592,
  correctPredictions: 80478,
  partialPredictions: 39937,
  incorrectPredictions: 39769,
  overallAccuracyRate: 63,
  top10PercentAccuracy: 82,
  top1PercentAccuracy: 91,
  domainCounts: {"주식시장":17974,"한국경제":15242,"가상자산":4810,"AI기술":10445,"거시경제":18182,"국제금융":11945,"금리통화정책":12654,"채권":7394,"외환":10069,"에너지":7329,"원자재":7113,"부동산":4678,"재정정책":4590,"반도체":7495,"사모투자":2507,"글로벌공급망":4630,"헤지펀드":4829,"미중관계":2379,"경제안보":4725,"지정학리스크":2133} as Record<string, number>,
  assetParticipation: {
    "gold": 28420,
    "sp500": 34180,
    "usd-krw": 22560,
    "kospi": 19840,
    "wti-oil": 21370,
    "nasdaq": 31250,
    "us-10y-yield": 18930,
    "dxy": 16780,
    "copper": 12640,
    "us-fed-rate": 24310,
    "kr-base-rate": 15620,
    "usd-jpy": 14850,
    "kosdaq": 11230,
    "semiconductor": 18940,
    "ai-tech": 22180,
    "ev-battery": 9870,
    "bio-pharma": 8340,
    "defense": 7520,
    "shipbuilding": 6890,
  } as Record<string, number>,
  institutionTypes: {
    "투자은행/증권사": 18420,
    "자산운용사/펀드": 22350,
    "대학/연구기관": 15680,
    "중앙은행/정부": 8940,
    "싱크탱크": 7230,
    "리서치하우스": 12580,
    "헤지펀드": 6340,
    "PE/VC": 4280,
    "독립 애널리스트/유튜버": 4180,
  } as Record<string, number>,
  countryDistribution: {"한국":40000,"호주":4421,"영국":8429,"캐나다":3863,"미국":13281,"일본":9990,"중국":9990,"이스라엘":587,"스위스":611,"폴란드":510,"싱가포르":460,"홍콩":518,"네덜란드":698,"스웨덴":514,"브라질":671,"대만":740,"인도":667,"프랑스":551,"UAE":531,"인도네시아":589,"이탈리아":652,"스페인":477,"터키":617,"독일":597} as Record<string, number>,
};
